### ISSUE TITLE
com.rakuten.tech.mobile.miniapp.MiniAppNotFoundException: Not Found: Server returned no mini app for the provided project ID.

### ISSUE THREAD

**Issue by George-Kihara** [rakutentech/android-miniapp#391]
**Describe the bug**
I am not able to open my website

**To Reproduce**
I'm following the sample code on your website
<img width="1643" alt="Screenshot 2021-11-16 at 13 34 00" src="https://user-images.githubusercontent.com/58682679/141969645-e1f15c04-4be2-40e5-ac37-ab243fb04dda.png">

But I keep getting this error
```
com.rakuten.tech.mobile.miniapp.MiniAppNotFoundException: Not Found: Server returned no mini app for the provided project ID.
        at com.rakuten.tech.mobile.miniapp.api.RetrofitRequestExecutor.exceptionForHttpError(ApiClient.kt:194)
        at com.rakuten.tech.mobile.miniapp.api.RetrofitRequestExecutor.executeRequest(ApiClient.kt:145)
        at com.rakuten.tech.mobile.miniapp.api.ApiClient.fetchInfo(ApiClient.kt:73)
        at com.rakuten.tech.mobile.miniapp.MiniAppDownloader.getMiniApp(MiniAppDownloader.kt:51)
        at com.rakuten.tech.mobile.miniapp.RealMiniApp.create(RealMiniApp.kt:69)
        at com.rakuten.tech.mobile.miniapp.MiniApp.create$default(MiniApp.kt:74)
```

**Expected behavior**
I expected to open my website

**Smartphone (please complete the following information):**
 - Sony xperia xa1 plus
 - Android 8.0
 - SDK Version 3.8.0

**Additional context**
Could the problem be the subscription key? Where do I get the key from?

**Comment by henrynguyen6677** [comment]
![image](https://user-images.githubusercontent.com/52127765/182427127-ff52d88b-81a3-422e-b2af-6bea9bbab4a5.png)
You create app link for mini app and set this value to MINIAPP_SERVER_BASE_URL

**Comment by Gidraf** [comment]
@George-Kihara Were you able to sort this out? Where can I find the subscription key?

**Comment by abeshjha** [comment]
@Gidraf any update on this? @henrynguyen6677  can you help us figure this out?

**Comment by abeshjha** [comment]
@rleojoseph  please help me on this. The documentation is not enough
